# Use lightweight Node image
FROM node:18.20.3-alpine3.19

# Create working directory
WORKDIR /app

# Copy only package files to leverage cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the app
COPY . .

# Expose port
EXPOSE 5000

# Run dev server
CMD ["npm", "run", "dev"]
